/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type IPFSUrl = string;

/**
 * A simple schema for storing a CID that represents the root of a pinset
 */
export interface Pinset {
  root: IPFSUrl;
  [k: string]: unknown;
}
